import { Inter } from "next/font/google";
import "./globals.css";

import { Provider } from "./Providers";

//to be changed :
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "1CS_Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
